<?php
/**
 * Template part for displaying Table of Contents
 *
 * @package TrendToday
 * @since 1.0.0
 */

// Check if TOC is enabled
$toc_enabled = get_option( 'trendtoday_toc_enabled', '1' );
if ( $toc_enabled !== '1' ) {
    return;
}

// Get TOC settings
$toc_position = get_option( 'trendtoday_toc_position', 'top' );
$toc_mobile_enabled = get_option( 'trendtoday_toc_mobile_enabled', '1' );
$toc_mobile_position = get_option( 'trendtoday_toc_mobile_position', 'floating' );
$toc_headings = get_option( 'trendtoday_toc_headings', array( 'h2', 'h3', 'h4' ) );
$toc_style = get_option( 'trendtoday_toc_style', 'nested' );
$toc_smooth_scroll = get_option( 'trendtoday_toc_smooth_scroll', '1' );
$toc_scroll_spy = get_option( 'trendtoday_toc_scroll_spy', '1' );
$toc_collapsible = get_option( 'trendtoday_toc_collapsible', '1' );
$toc_sticky = get_option( 'trendtoday_toc_sticky', '0' );
$toc_auto_collapse_mobile = get_option( 'trendtoday_toc_auto_collapse_mobile', '1' );
$toc_min_headings = get_option( 'trendtoday_toc_min_headings', 2 );
$toc_title = get_option( 'trendtoday_toc_title', __( 'สารบัญ', 'trendtoday' ) );

// Build data attributes for JavaScript
$toc_data = array(
    'headings' => implode( ',', $toc_headings ),
    'style' => $toc_style,
    'smoothScroll' => $toc_smooth_scroll === '1',
    'scrollSpy' => $toc_scroll_spy === '1',
    'collapsible' => $toc_collapsible === '1',
    'sticky' => $toc_sticky === '1',
    'minHeadings' => absint( $toc_min_headings ),
    'title' => $toc_title,
    'mobileEnabled' => $toc_mobile_enabled === '1',
    'mobilePosition' => $toc_mobile_position,
    'autoCollapseMobile' => $toc_auto_collapse_mobile === '1',
);

$toc_classes = array(
    'trendtoday-toc',
    'trendtoday-toc-' . esc_attr( $toc_position ),
    'trendtoday-toc-style-' . esc_attr( $toc_style ),
);

if ( $toc_sticky === '1' ) {
    $toc_classes[] = 'trendtoday-toc-sticky';
}

if ( $toc_collapsible === '1' ) {
    $toc_classes[] = 'trendtoday-toc-collapsible';
}

if ( $toc_mobile_enabled === '1' ) {
    $toc_classes[] = 'trendtoday-toc-mobile-' . esc_attr( $toc_mobile_position );
}

if ( $toc_auto_collapse_mobile === '1' ) {
    $toc_classes[] = 'trendtoday-toc-auto-collapse-mobile';
}
?>

<div class="<?php echo esc_attr( implode( ' ', $toc_classes ) ); ?>" 
     data-toc-config='<?php echo esc_attr( json_encode( $toc_data ) ); ?>'>
    <div class="trendtoday-toc-container">
        <?php if ( $toc_collapsible === '1' ) : ?>
            <button class="trendtoday-toc-toggle" aria-label="<?php echo esc_attr( $toc_title ); ?>">
                <span class="trendtoday-toc-title">
                    <i class="fas fa-list-ul"></i>
                    <?php echo esc_html( $toc_title ); ?>
                </span>
                <i class="fas fa-chevron-down trendtoday-toc-icon"></i>
            </button>
        <?php else : ?>
            <div class="trendtoday-toc-header">
                <h3 class="trendtoday-toc-title">
                    <i class="fas fa-list-ul"></i>
                    <?php echo esc_html( $toc_title ); ?>
                </h3>
            </div>
        <?php endif; ?>
        
        <div class="trendtoday-toc-content">
            <nav class="trendtoday-toc-nav" role="navigation" aria-label="<?php echo esc_attr( $toc_title ); ?>">
                <!-- TOC will be generated by JavaScript -->
            </nav>
        </div>
    </div>
</div>

<?php if ( $toc_mobile_enabled === '1' && $toc_mobile_position === 'floating' ) : ?>
    <!-- Mobile Floating TOC Button -->
    <button class="trendtoday-toc-mobile-toggle fixed bottom-20 left-4 z-40 bg-accent text-white w-14 h-14 rounded-full shadow-lg flex items-center justify-center hover:bg-orange-600 transition md:hidden" 
            aria-label="<?php echo esc_attr( $toc_title ); ?>">
        <i class="fas fa-list text-xl"></i>
    </button>
    
    <!-- Mobile TOC Drawer -->
    <div class="trendtoday-toc-mobile-drawer fixed inset-0 z-50 bg-black/50 backdrop-blur-sm hidden md:hidden">
        <div class="trendtoday-toc-mobile-content bg-white h-full w-80 max-w-[85vw] shadow-2xl transform transition-transform">
            <div class="flex items-center justify-between p-4 border-b border-gray-200">
                <h3 class="font-bold text-lg"><?php echo esc_html( $toc_title ); ?></h3>
                <button class="trendtoday-toc-mobile-close w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center text-gray-500 hover:bg-gray-200 transition">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="trendtoday-toc-mobile-nav p-4 overflow-y-auto h-[calc(100%-65px)]">
                <!-- TOC will be generated by JavaScript -->
            </div>
        </div>
    </div>
<?php endif; ?>
